name: Docker Image build

on:
  push:
    branches:
      - 'dev'
  pull_request:
    branches:
      - 'master'
      - 'dev'

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm'
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build image
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: lucaam/rpi-cups:latest